services:
  postgres-test:
    image: postgres:17.5-alpine3.22
    container_name: test_postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: pomodoro-test
    ports:
      - "5430:5432"

  worker:
    command: celery -A worker.celery worker --loglevel=info
    depends_on:
      - redis-test

  redis-test:
    image: redis:8.0.2-alpine
    restart: always
    ports:
      - '6379:6379'
