"""update-user-profile2

Revision ID: 033ae3f423c3
Revises: 71ea2336acdd
Create Date: 2025-06-18 15:46:28.289032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033ae3f423c3'
down_revision: Union[str, None] = '71ea2336acdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
